# Site settings
baseurl = "http://szop-precz.zubala.com/"
languageCode = "en-US"
builddrafts = false
canonifyurls = false
author = "Aleksander Zubala"
title = "SzopPrecz"
theme = "hugo-freelancer-theme"
contentdir = "content"
layoutdir = "layouts"
publishdir = "../"

DefaultContentLanguage = "en"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "SzopPrecz"
    description = "Mobile App for checking shops availability in Poland"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "szop-precz@zubala.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "SzopPrecz"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "SzopPrecz"
        subtitle = "Stop wondering if shops are opened this Sunday!"


    [params.about]
        title = "About"
        left = "“SzopPrecz” (eng. Raccoon) is simple yet useful application for checking shops availability in Poland. Starting from March 2018, shops will be closed on some Sundays (enforced by law), which leaves a burden of remembering the schedule. "
        right = "Enter “SzopPrecz” — whether you’re a resident or just visiting Poland, it’s an easy way to check if shops are opened. You can easily check shops availability for current day and schedule notification for upcoming shops close downs."

        [params.about.button]
            text = "AppStore"
            link = "//itunes.apple.com/us/app/szop-precz/id1348257936?ls=1&mt=8"
            icon = "fab fa-apple"


    [params.contact]
        title = "Feedback"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.message]
            text = "Feedback"
            error = "Please provide your feedback about the app"

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.legal]
            title = "Legal"
            privacypolicy = "[Privacy Policy](privacy-policy.html)"
            useragreement = "[User Agreement](user-agreement.html)"

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link = "//facebook.com/SzopPrecz"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/SzopPrecz"


        [params.footer.credits]
            title = "About Author"
            text = "SzopPrecz is created by [Aleksander Zubala](//zubala.com)"

[languages]

[languages.pl]
title = "SzoPrecz - zakaz handlu w niedziele nie straszny"
name = "SzopPrecz"
description = "SzopPrecz -- to prosta aczkolwiek użyteczna aplikacja służąca do sprawdzania dostępności sklepów w Polsce."

[languages.pl.header]
subtitle = "Nie zastanawiaj się czy zrobisz zakupy w tę niedzielę -- Szop Ci przypomni!"

[languages.pl.about]
title = "O Aplikacji"
left = "“SzopPrecz” to prosta aczkolwiek użyteczna aplikacja służąca do sprawdzania dostępności sklepów w Polsce. Od początku marca 2018, zgodnie z polskim prawem, większość sklepów będzie zamkniętych w wybrane niedziele i święta. Tym samym, powstaje problem i niepewność czy danego dnia zrobimy zakupy."
right = "Na pomoc przybywa Szop Precz! Pozbądź się tej nieprzyjemnej niepewności i sprawdź dostępność sklepów! Możesz też ustawić powiadomienie o dniach, w kórych sklepy będą zamknięte oraz przeglądać terminy zamknięcia sklepów w 2018"

[languages.pl.about.button]
link = "//itunes.apple.com/pl/app/szop-precz/id1348257936?ls=1&mt=8"
icon = "fab fa-apple"
text = "AppStore"

[languages.pl.contact]
title = "Kontakt"

# 'error' defines error messages for invalid inputs
[languages.pl.contact.form.name]
text = "Imię"
error = "Podaj swoje imię"

[languages.pl.contact.form.email]
text = "Adres E-mail"
error = "Podaj swój adres e-mail"

[languages.pl.contact.form.message]
text = "Kontakt"
error = "Podaj treść wiadomości"

[languages.pl.contact.form.button]
text = "Wyślij"

[languages.pl.footer]
copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

[languages.pl.footer.legal]
title = "Informacje Prawne"
privacypolicy = "[Privacy Policy](privacy-policy.html)"
useragreement = "[User Agreement](user-agreement.html)"

[languages.pl.footer.social]
title = "Portale Społecznościowe"
# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
# for more icons. The icons are represented by their corresponding
# CSS class.
[[languages.pl.footer.social.networks]]
    icon = "fa-facebook"
    link = "//facebook.com/SzopPrecz"

[[languages.pl.footer.social.networks]]
    icon = "fa-twitter"
    link=  "//twitter.com/SzopPrecz"


[languages.pl.footer.credits]
title = "Autor"
text = "SzopPrecz jest tworzony przez [Aleksandra Zubala](//zubala.com)"




